AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway HTTP API with custom domain for NixSearch MCP Lambda

Parameters:
  FunctionName:
    Type: String
    Default: NixSearchMCP
    Description: Name of the existing Lambda function

  DomainName:
    Type: String
    Default: search.nix.mcp.playday3008.dev
    Description: Custom domain name for the API

  CertificateArn:
    Type: String
    Description: ARN of the validated ACM certificate for the custom domain

Resources:
  # HTTP API (v2)
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${FunctionName}-API'
      ProtocolType: HTTP

  # Lambda proxy integration
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionName}'
      PayloadFormatVersion: '2.0'

  # Default catch-all route
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: $default
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Auto-deploy stage
  DefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: $default
      AutoDeploy: true

  # Permission for API Gateway to invoke the Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionName
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*'

  # Custom domain name
  CustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref CertificateArn

  # Map the custom domain to the API
  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn: DefaultStage
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref CustomDomain
      Stage: $default

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt HttpApi.ApiEndpoint

  CustomDomainTarget:
    Description: Regional domain name — create a CNAME in CloudFlare pointing to this value
    Value: !GetAtt CustomDomain.RegionalDomainName

  CustomDomainUrl:
    Description: Custom domain URL (available after CloudFlare CNAME is configured)
    Value: !Sub 'https://${DomainName}'
